version: '3'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - app
  app:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: wait-for db:3306 -t 300
    command: node server.js
    volumes:
      - ./node:/usr/src/app    
    tty: true
    depends_on: 
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
